"""
Django settings for Taiga2 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5$ucnfiv#k5=4r_nu+w-phaeki8!co4gh!zqd$f^lll=3yc$o9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'Issue_Tracker',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'storages',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # debe ir antes
    'allauth.account.middleware.AccountMiddleware',             # aquí lo añades
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AWS_ACCESS_KEY_ID = 'ASIA2KPQ6TKJXVPDJYUG'
AWS_SECRET_ACCESS_KEY = '4PoIeHwIt8iqmUGz+rAE1t0w7FiX7eIAKJEDdgIX'
AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjEBoaCXVzLXdlc3QtMiJHMEUCIBlB34O9sls/NfJP3ZUZ6yUchwojvitTITChHcR645jUAiEAplmjEaUJQ1hPwYE3rGTRBRD0sawmq4maPZKRdrqZaocqxgIIk///////////ARAAGgw3MDk3MTE3OTY4ODMiDHrGlJq7xBsTRQ4OBiqaAmix9NvocspXy0s4yteM9xahZwCZql/+QoIrXpxyH+CAkQBUZOuYzR60gA0f9KPzXrPEstCGfHXZzMFpsC1V1p5jEfQfVCoASQ+ppSw0m/OJlHxEytTLAqbCeLBHlVFH6pSluJNwjTILXDyoidnKw+AT342F9BIGlQ6e6DQ9sAn+WBjEn7AqJifv0QQJL3a0wjDirEFR4kWIpEeYK4amFD3IZZM1cp6X+D4LWjCMPhLPOJsrnVkndBLyik7layzq/Wnagvaa4oa/ZoEY0KLo5kPgqiE/77uKH/Q3s3hdfuHUD2m8y2CG/hVjqBWCtgID034DKSukxeJIVemTxE/2lTlF+Bt+QkZGnYnb2XWT9xJOKZgdBKKNo/jFDzD12dq/BjqdAcOHXN9crLdgVBe8ToG9lIgmeuiocU2XIdP1NM2twiK81MsALT+Q450w2a37TAq+gOEU4rCsPRDC5cfbbeJ+1cXM/yW21n9XT1HNmwdRrXIb/KjPsrIxcyi6Cb80zFpTvF6VobEAQgu2HrwRsRZpEq487bmLiYpu44hUncImlwX+ggAkhUX5Aez0+UGTUTvrvPGymMfK05F2UapjIfc='
AWS_STORAGE_BUCKET_NAME = 'issuetracker34'
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'private'


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_LOCATION = 'attachments'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
AWS_DEFAULT_ACL = 'public-read'

ROOT_URLCONF = 'Taiga2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Taiga2.wsgi.application'
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}
SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = 'http://127.0.0.1:8000/api/custom-issues'
LOGOUT_REDIRECT_URL = 'http://127.0.0.1:8000/api/custom-issues'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'ATHnpvdGVFoIUjktuHGQgkFHciwkLsOL',
        'HOST': 'centerbeam.proxy.rlwy.net',
        'PORT': '16317',
        'OPTIONS': {'sslmode': 'require'},
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
